- hosts: master
  vars_files:
    - cns_values.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:
   - set_fact: 
       cns_docker: "{{ cns_docker }}"
       cns_nvidia_driver: "{{ cns_nvidia_driver }}"
       cns_validation: "{{ cns_validation }}"

   - name: Get Nvidia Tegra Release
     shell: uname -r | awk -F'-' '{print $2}'
     register: release

   - set_fact:
       release: "{{ release.stdout }}"

   - name: Check Current Running Cloud Native Stack Version
     shell: kubectl version -o json | jq .serverVersion.gitVersion | sed 's/\"//g'
     register: k8sversion

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.29.2'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 12.1

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.29.4'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 12.2

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.29.6'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 12.3

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.30.0'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 13.1

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.30.2'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 13.2

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.30.6'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 13.3

   - name: Create Cloud Native Stack cns_version.yaml
     when: "k8sversion.stdout == 'v1.31.2'"
     copy:
       dest: "/tmp/cns_version.yaml"
       content: |
         cns_version: 14.1

   - name: Fetch cns_version.yaml
     ansible.builtin.fetch:
       src: "/tmp/cns_version.yaml"
       dest: "{{lookup('pipe', 'pwd')}}/cns_version.yaml"
       flat: yes

   - name: Update the cns version in cns_values.yaml
     shell: |
       version=$(cat {{lookup('pipe', 'pwd')}}/cns_version.yaml | awk -F':' '{print $2}' | head -n1 | tr -d ' ' | tr -d '\n\r');  driver_version=$(cat {{lookup('pipe', 'pwd')}}/cns_values_$version.yaml | grep driver_version | awk -F':' '{print $2}' | head -n1 | tr -d ' ' | tr -d '\n\r')
       cp -r {{lookup('pipe', 'pwd')}}/cns_values_$version.yaml {{lookup('pipe', 'pwd')}}/cns_values.yaml
#       sed -i "s/cns_version: .*/cns_version: $version/g; s/gpu_driver_version: .*/gpu_driver_version: $driver_version/g" {{lookup('pipe', 'pwd')}}/cns_values.yaml

   - name: Update the cns_values
     when: cns_docker == true and cns_nvidia_driver == true
     replace:
       path: "{{lookup('pipe', 'pwd')}}/cns_values.yaml"
       regexp: '{{ item.regex }}'
       replace: '{{ item.replace }}'
     with_items:
       - { regex: 'cns_docker: no', replace: 'cns_docker: yes' }
       - { regex: 'cns_nvidia_driver: no', replace: 'cns_nvidia_driver: yes' }

- import_playbook: prerequisites.yaml

- import_playbook: nvidia-driver.yaml
  when: "release != 'tegra' and cns_nvidia_driver == true"

- hosts: master
  vars_files:
    - cns_values.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:
   - name: Validate whether Kubernetes cluster installed
     shell: kubectl cluster-info
     register: k8sup
     no_log: True
     failed_when: false

   - name: Check Current Running Cloud Native Stack Version
     shell: kubectl version -o json | jq .serverVersion.gitVersion | sed 's/\"//g'
     register: k8sversion

   - name: Upgrade the Cloud Native Stack from 14.0 to 14.1
     shell: kubeadm upgrade apply v1.31.6 --force --ignore-preflight-errors=CreateJob
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.31.2'"
     become: true

   - name: Upgrade the Cloud Native Stack from 13.2 to 13.3
     shell: kubeadm upgrade apply v1.30.10 --force --ignore-preflight-errors=CreateJob
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.30.6'"
     become: true

   - name: Upgrade the Cloud Native Stack from 13.1 to 13.2
     shell: kubeadm upgrade apply v1.30.5 --force
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.30.2'"
     become: true

   - name: Upgrade the Cloud Native Stack from 13.0 to 13.1
     shell: kubeadm upgrade apply v1.30.2 --force
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.30.0'"
     become: true

   - name: Upgrade the Cloud Native Stack from 12.2 to 12.3
     shell: kubeadm upgrade apply v1.29.9 --force
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.29.6'"
     become: true

   - name: Upgrade the Cloud Native Stack from 12.1 to 12.2
     shell: kubeadm upgrade apply v1.29.6 --force
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.29.4'"
     become: true

   - name: Upgrade the Cloud Native Stack from 12.0 to 12.1
     shell: kubeadm upgrade apply v1.29.4 --force
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.29.2'"
     become: true

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack 13.3 or 14.1
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.30.6' and release != 'tegra' or 'running' in k8sup.stdout and k8sversion.stdout == 'v1.31.2' and release != 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack 12.3 or 13.2
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.29.6' and release != 'tegra' or 'running' in k8sup.stdout and k8sversion.stdout == 'v1.30.2' and release != 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack 12.2 or 11.3 or 13.1
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.29.4' and release != 'tegra' or 'running' in k8sup.stdout and k8sversion.stdout == 'v1.28.8' and release != 'tegra'  or 'running' in k8sup.stdout and k8sversion.stdout == 'v1.30.0' and release != 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.4/manifests/calico.yaml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack 12.1 or 11.2 or 10.5 
     when: "'running' in k8sup.stdout and k8sversion.stdout == 'v1.29.2' and release != 'tegra' or 'running' in k8sup.stdout and k8sversion.stdout == 'v1.28.6' and release != 'tegra'  or 'running' in k8sup.stdout and k8sversion.stdout == 'v1.27.10' and release != 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/calico.yaml

   - name: Update Network plugin for Calico on NVIDIA Cloud Native Stack > 3.1
     when: "'running' in k8sup.stdout and release != 'tegra'"
     shell: "sleep 5; kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=ens*,eth*,enc*,bond*,enp*,eno*"

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack
     when: "k8sversion.stdout == 'v1.29.2' and release == 'tegra' or k8sversion.stdout == 'v1.28.6' and release == 'tegra' or k8sversion.stdout == 'v1.27.10' and release == 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.25.1/Documentation/kube-flannel.yml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack
     when: "k8sversion.stdout == 'v1.29.4' and release == 'tegra' or k8sversion.stdout == 'v1.28.8' and release == 'tegra' or k8sversion.stdout == 'v1.30.0' and release == 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.25.5/Documentation/kube-flannel.yml

   - name: Install networking plugin to kubernetes cluster on NVIDIA Cloud Native Stack
     when: "k8sversion.stdout == 'v1.29.6' and release == 'tegra' or k8sversion.stdout == 'v1.30.2' and release == 'tegra'"
     command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.25.6/Documentation/kube-flannel.yml

   - pause:
       seconds: 15

   - name: Get Node name
     shell: "kubectl get nodes  | awk '{print $1}' | grep -v NAME"
     register: node_name
     no_log: True
     failed_when: false

   - name: Uncordon the nodes
     shell: "kubectl uncordon {{ item }}"
     with_items: "{{ node_name.stdout_lines }}"
     no_log: True
     failed_when: false

- import_playbook: operators-upgrade.yaml
  when: "release != 'tegra' "